import 'dart:typed_data';

import 'package:cross_file/cross_file.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/prediction.dart';
import 'pdf_report_service_stub.dart' if (dart.library.io) 'pdf_report_service_io.dart';

export 'pdf_report_service_stub.dart' if (dart.library.io) 'pdf_report_service_io.dart' show writePdfBytes;

class PdfReportService {
  static Future<Uint8List> buildRecommendationPdfBytes(PredictionResult r, String businessName) async {
    return _recommendationDoc(r, businessName).save();
  }

  static pw.Document _recommendationDoc(PredictionResult r, String businessName) {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        build: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('SME Advisor — Financing Report', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Text('Business: $businessName'),
            pw.Divider(),
            pw.Text('Recommendation: ${r.recommendationType}'),
            pw.Text('Product: ${r.productName}'),
            pw.Text('Cash preserved: RM ${r.cashPreservedRm.toStringAsFixed(2)}'),
            pw.Text('Additional cost: RM ${r.additionalCostRm.toStringAsFixed(2)}'),
            pw.Text('Confidence: ${(r.confidence * 100).toStringAsFixed(1)}%'),
            pw.SizedBox(height: 12),
            pw.Text(r.explanation),
          ],
        ),
      ),
    );
    return doc;
  }

  static Future<Uint8List> buildFullReportBytes(Map<String, dynamic> report) async {
    return _fullReportDoc(report).save();
  }

  static Future<XFile> saveFullReport(Map<String, dynamic> report) async {
    final bytes = await buildFullReportBytes(report);
    return writePdfBytes(bytes, 'sme_advisor_full_report.pdf');
  }

  static pw.Document _fullReportDoc(Map<String, dynamic> report) {
    final health = report['health'] as Map<String, dynamic>? ?? {};
    final kpis = report['kpis'] as Map<String, dynamic>? ?? {};
    final grants = report['grant_matches'] as List<dynamic>? ?? [];
    final alerts = report['alerts'] as List<dynamic>? ?? [];

    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        build: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('SME Advisor — Readiness & Grant Pack', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 6),
            pw.Text('${report['business_name']} · ${report['industry']}'),
            pw.Divider(),
            pw.Text(
              'Readiness: ${health['health_score']}/100 · Grade ${health['health_grade']} · ${health['health_label']}',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(health['pitch_line']?.toString() ?? ''),
            pw.SizedBox(height: 12),
            pw.Text('Cash & runway', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.Text('Days cash on hand: ${kpis['days_cash_on_hand']}'),
            pw.Text('Runway (est.): ${report['runway_days_est']} days'),
            pw.Text('Net operating cash: RM ${kpis['net_operating_cash_rm']}'),
            pw.SizedBox(height: 12),
            pw.Text('Alerts', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            ...alerts.map((a) => pw.Text('• $a')),
            pw.SizedBox(height: 12),
            pw.Text('Grant matches', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            ...grants.take(6).map((g) {
              final m = g as Map<String, dynamic>;
              return pw.Text('• ${m['scheme_name']} (${m['agency']})');
            }),
            pw.SizedBox(height: 12),
            pw.Text('Compliance snapshot', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.Text('e-Invoice Phase 4 (RM1M–RM5M): Jan 2026'),
            pw.Text('e-Invoice Phase 5 (<RM1M): Jul 2026'),
            pw.Text('Minimum wage RM1,700: Feb 2025'),
            pw.Spacer(),
            pw.Text('Generated by SME Advisor · APC2026 demo', style: const pw.TextStyle(fontSize: 9)),
          ],
        ),
      ),
    );
    return doc;
  }
}
